# This is a basic workflow to help you get started with Actions

name: Create card for all new issues

# Controls when the workflow will run
on:
  issues:
    types: [opened]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createCard:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Runs a single command using the runners shell
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Product Management
          column-name: New Issue
