name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        machines: [1, 2, 3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:8080
          record: true
          parallel: true
          group: Parallel 3x on ${{ matrix.os }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
